import { StyleSheet } from 'react-native'
import { Colors } from '../../../constants/colors'
import { rgbaFromHex } from './stakeStyles'

export const stepStakeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  chipsWrap: { marginHorizontal: 16, marginTop: 8, marginBottom: 12, flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: Colors.cardAlt,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
  },
  chipText: { color: Colors.text, fontSize: 13, fontWeight: '700' },
  chipSep: { color: Colors.textMuted, fontSize: 13 },
  chipAction: { color: Colors.accentLight, fontSize: 13, fontWeight: '600' },
  searchWrap: {
    marginBottom: 12,
    backgroundColor: Colors.cardAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchIcon: { color: Colors.textMuted, fontSize: 14 },
  searchInput: { flex: 1, color: Colors.text, paddingVertical: 10, fontSize: 14 },
  friendRow: {
    marginBottom: 8,
    padding: 14,
    borderRadius: 12,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
  },
  friendRowSelected: {
    backgroundColor: rgbaFromHex(Colors.accent, 0.12),
    borderLeftWidth: 3,
    borderLeftColor: Colors.accent,
  },
  friendAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.cardAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  friendAvatarText: { color: Colors.accentLight, fontWeight: '700', fontSize: 14 },
  friendCenter: { flex: 1, marginHorizontal: 12 },
  friendNick: { color: Colors.text, fontSize: 15, fontWeight: '700' },
  friendActivity: { color: Colors.textMuted, fontSize: 12, marginTop: 2 },
  friendStakeWrap: { flexDirection: 'row', alignItems: 'center', marginRight: 8, gap: 4 },
  friendStakeInput: {
    width: 60,
    backgroundColor: Colors.background,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    color: Colors.text,
    fontWeight: '700',
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    textAlign: 'center',
  },
  friendStakeSuffix: { color: Colors.textMuted, fontSize: 12 },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: rgbaFromHex(Colors.text, 0.3),
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxSelected: { backgroundColor: Colors.accent, borderColor: Colors.accent },
  checkboxText: { color: Colors.white, fontSize: 12, fontWeight: '700' },
  inviteCard: {
    marginTop: 8,
    padding: 14,
    borderRadius: 12,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: rgbaFromHex(Colors.text, 0.2),
    flexDirection: 'row',
    alignItems: 'center',
  },
  inviteIconWrap: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.cardAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inviteIcon: { color: Colors.accentLight, fontSize: 12, fontWeight: '700' },
  inviteTextWrap: { flex: 1, marginHorizontal: 12, gap: 2 },
  inviteTitle: { color: Colors.text, fontSize: 14 },
  inviteSub: { color: Colors.textMuted, fontSize: 12 },
  copyBtn: { backgroundColor: Colors.accent, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 6 },
  copyBtnText: { color: Colors.white, fontSize: 13, fontWeight: '700' },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    backgroundColor: Colors.background,
  },
  footerFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: -16,
    height: 16,
    backgroundColor: rgbaFromHex(Colors.background, 0.6),
  },
  submitButton: {
    height: 52,
    borderRadius: 14,
    backgroundColor: Colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  submitButtonDisabled: { backgroundColor: Colors.cardAlt },
  submitMain: { color: Colors.white, fontSize: 15, fontWeight: '700' },
  submitMainDisabled: { color: Colors.textMuted },
  submitSub: { color: rgbaFromHex(Colors.text, 0.6), fontSize: 11 },
})
