import { StyleSheet } from 'react-native'
import { Colors } from '../../constants/colors'

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  friendBanner: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  friendBannerAvatar: { color: Colors.accentLight, fontWeight: '700' },
  friendBannerText: { color: Colors.text, fontSize: 14 },
  stepBody: { flex: 1, padding: 16 },
  searchInput: {
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: 12,
    color: Colors.text,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
  },
  sectionTitle: { color: Colors.textMuted, marginBottom: 8, marginTop: 8, fontSize: 12, fontWeight: '700' },
  gameRow: {
    height: 56,
    backgroundColor: Colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  emoji: { fontSize: 22, marginRight: 10 },
  gameName: { flex: 1, color: Colors.text, fontSize: 15, fontWeight: '600' },
  chevron: { color: Colors.textMuted, fontSize: 16 },
  emptyState: { color: Colors.textMuted, marginTop: 12, textAlign: 'center' },
  chipsRow: { marginBottom: 12 },
  participantChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 8,
    gap: 8,
  },
  avatarText: { color: Colors.accentLight, fontWeight: '700', width: 18 },
  participantNick: { color: Colors.text, fontSize: 13 },
  removeText: { color: Colors.textMuted, fontSize: 13 },
  friendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    padding: 12,
    marginBottom: 8,
  },
  friendRowSelected: { borderColor: Colors.accent, backgroundColor: Colors.cardAlt },
  friendNick: { flex: 1, color: Colors.text, fontSize: 14, fontWeight: '600' },
  check: { color: Colors.accent, fontWeight: '700' },
  stickyFooter: { paddingTop: 8 },
  button: { backgroundColor: Colors.accent, borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 10 },
  buttonDisabled: { opacity: 0.4 },
  buttonText: { color: Colors.white, fontSize: 15, fontWeight: '700' },
  formatCard: {
    backgroundColor: Colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    padding: 16,
    marginBottom: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 10,
  },
  formatCardSelected: { borderColor: Colors.accent, backgroundColor: Colors.cardAlt },
  formatIcon: { color: Colors.accentLight, fontSize: 12, fontWeight: '700' },
  formatMain: { flex: 1 },
  formatName: { color: Colors.text, fontSize: 15, fontWeight: '700' },
  formatDesc: { color: Colors.textMuted, fontSize: 12, marginTop: 2 },
  radio: { width: 18, height: 18, borderRadius: 9, borderWidth: 1, borderColor: Colors.borderSoft },
  radioSelected: { borderColor: Colors.accent, backgroundColor: Colors.accent },
  bestOfPicker: { width: '100%', flexDirection: 'row', gap: 8, marginTop: 8 },
  bestOfOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    backgroundColor: Colors.cardAlt,
  },
  bestOfOptionSelected: { borderColor: Colors.accent, backgroundColor: Colors.accent },
  bestOfText: { color: Colors.text, fontWeight: '600' },
  pokerConfig: { width: '100%', marginTop: 10, gap: 8 },
  pokerTitle: { color: Colors.textMuted, fontSize: 12, fontWeight: '600' },
  pokerModeRow: { flexDirection: 'row', gap: 8 },
  perMatchStakeRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
    flexWrap: 'wrap',
  },
  perMatchStakeLabel: { color: Colors.textMuted, fontSize: 13, fontWeight: '600' },
  perMatchStakeInput: {
    minWidth: 72,
    backgroundColor: Colors.cardAlt,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: 10,
    color: Colors.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    fontWeight: '700',
  },
  perMatchStakeSuffix: { color: Colors.text, fontSize: 14, fontWeight: '600' },
  stakeOption: {
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  stakeOptionSelected: { borderColor: Colors.accent },
  stakeTitle: { color: Colors.text, fontSize: 15, fontWeight: '700' },
  stakeDesc: { color: Colors.textMuted, fontSize: 12, marginTop: 2 },
  stakeConfig: { marginTop: 10 },
  stakeInput: {
    backgroundColor: Colors.cardAlt,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: 10,
    color: Colors.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  stakeModeRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  modeBtn: {
    flex: 1,
    backgroundColor: Colors.cardAlt,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    paddingVertical: 10,
    alignItems: 'center',
  },
  modeBtnSelected: { borderColor: Colors.accent, backgroundColor: Colors.accent },
  modeBtnText: { color: Colors.text, fontSize: 12, fontWeight: '700' },
  customStakeRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 8 },
  customStakeName: { flex: 1, color: Colors.text, fontSize: 14 },
  stakeInputSmall: {
    width: 90,
    backgroundColor: Colors.cardAlt,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: 10,
    color: Colors.text,
    paddingHorizontal: 10,
    paddingVertical: 8,
    textAlign: 'center',
  },
  poolPreview: { color: Colors.green, fontSize: 13, fontWeight: '600', marginTop: 6 },
  submitButton: {
    marginTop: 12,
    marginBottom: 24,
    backgroundColor: Colors.accent,
    borderRadius: 12,
    alignItems: 'center',
    paddingVertical: 15,
  },
  submitText: { color: Colors.white, fontWeight: '700', fontSize: 15 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12 },
  backBtn: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  backIcon: { color: Colors.text, fontSize: 18 },
  headerTitle: { color: Colors.text, fontSize: 16, fontWeight: '700' },
  headerStep: { color: Colors.textMuted, fontSize: 13 },
  progressTrack: { height: 2, backgroundColor: Colors.borderSoft },
  progressFill: { height: 2, backgroundColor: Colors.accent },
})
