import { StyleSheet } from 'react-native'
import { Colors } from '../../constants/colors'

export const rivalryScreenStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  list: { flex: 1, backgroundColor: Colors.background },
  listContent: { paddingBottom: 100 },
  header: {
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.cardAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBtnText: { color: Colors.text, fontSize: 16, fontWeight: '700' },
  sectionLabel: {
    marginLeft: 16,
    marginTop: 16,
    marginBottom: 8,
    color: Colors.textMuted,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  emptyRow: { paddingHorizontal: 16, paddingVertical: 12 },
  emptyText: { color: Colors.textMuted, fontSize: 13 },
  bottomActions: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.background,
    paddingHorizontal: 16,
    paddingTop: 8,
    flexDirection: 'row',
    gap: 8,
  },
  newBetBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    backgroundColor: Colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  newBetText: { color: Colors.white, fontSize: 15, fontWeight: '700' },
  rematchBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rematchText: { color: Colors.text, fontSize: 15, fontWeight: '700' },
})
