import type { GameTemplate } from './types'

export const SPORT_GAME_TEMPLATES: GameTemplate[] = [
  {
    id: 'pilkarzyki',
    name: 'Piłkarzyki',
    emoji: '⚽',
    category: 'sport',
    resultType: 'score',
    scoringLabel: 'Bramki',
  },
  {
    id: 'ping_pong',
    name: 'Ping pong',
    emoji: '🏓',
    category: 'sport',
    resultType: 'score',
    scoringLabel: 'Punkty',
  },
  {
    id: 'dart',
    name: 'Dart',
    emoji: '🎯',
    category: 'sport',
    resultType: 'legs',
    scoringLabel: 'Legi',
  },
  {
    id: 'koszykowka',
    name: 'Koszykówka 1v1',
    emoji: '🏀',
    category: 'sport',
    resultType: 'score',
    scoringLabel: 'Punkty',
  },
  {
    id: 'tenis',
    name: 'Tenis',
    emoji: '🎾',
    category: 'sport',
    resultType: 'sets',
    scoringLabel: 'Sety',
  },
  {
    id: 'badminton',
    name: 'Badminton',
    emoji: '🏸',
    category: 'sport',
    resultType: 'score',
    scoringLabel: 'Punkty',
  },
  {
    id: 'bilard',
    name: 'Bilard',
    emoji: '🎱',
    category: 'sport',
    resultType: 'winner_only',
    scoringLabel: null,
  },
  {
    id: 'bowling',
    name: 'Bowling',
    emoji: '🎳',
    category: 'sport',
    resultType: 'score',
    scoringLabel: 'Punkty',
  },
]
