import { StyleSheet } from "react-native";
import { Colors } from "@/shared/constants/colors";
import { hexToRgba } from "@/shared/utils/colors";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background },
  content: { paddingBottom: 32 },
  header: {
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: { color: Colors.text, fontSize: 20, fontWeight: "700" },
  headerActions: { flexDirection: "row", gap: 8 },
  searchBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.cardAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  searchBtnText: { color: Colors.textMuted, fontSize: 14 },
  sectionLabel: {
    marginLeft: 16,
    marginBottom: 12,
    marginTop: 8,
    color: Colors.textMuted,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  listWrap: { paddingHorizontal: 16, gap: 8 },
  playBadge: {
    backgroundColor: hexToRgba(Colors.amber, 0.15),
    borderRadius: 20,
    paddingVertical: 4,
    paddingHorizontal: 12,
  },
  playBadgeText: { color: Colors.amber, fontSize: 12, fontWeight: "700" },
  inviteCard: {
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: Colors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    padding: 16,
  },
  inviteCodeDisplay: {
    color: Colors.text,
    fontSize: 28,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
    letterSpacing: 2,
    textAlign: "center",
    marginBottom: 16,
  },
  inviteCodeMono: { fontFamily: "monospace" },
  loadingCode: {
    color: Colors.textMuted,
    fontSize: 16,
    textAlign: "center",
    marginBottom: 16,
  },
  rowBtns: { flexDirection: "row", gap: 8, marginBottom: 10 },
  smallBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: Colors.cardAlt,
    alignItems: "center",
  },
  smallBtnText: { color: Colors.accentLight, fontSize: 14, fontWeight: "600" },
  shareBtn: {
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: Colors.accent,
    alignItems: "center",
  },
  shareBtnText: { color: Colors.white, fontSize: 15, fontWeight: "700" },
  codeInput: {
    backgroundColor: Colors.cardAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: Colors.text,
    fontSize: 18,
    fontFamily: "monospace",
    letterSpacing: 1,
  },
  fieldMessage: { marginTop: 8, fontSize: 13 },
  fieldError: { color: Colors.red },
  fieldSuccess: { color: Colors.green },
  addBtn: {
    marginTop: 14,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: Colors.accent,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
  },
  addBtnDisabled: { backgroundColor: Colors.cardAlt, opacity: 0.6 },
  addBtnText: { color: Colors.white, fontSize: 15, fontWeight: "700" },
  addBtnTextDisabled: { color: Colors.textMuted },
});

export const betInviteStyles = StyleSheet.create({
  card: {
    backgroundColor: Colors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: hexToRgba(Colors.accent, 0.3),
    padding: 16,
  },
  top: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  from: { color: Colors.text, fontSize: 15, fontWeight: "700" },
  game: { color: Colors.textMuted, fontSize: 12, marginTop: 2 },
  stake: { color: Colors.accentLight, fontSize: 16, fontWeight: "700" },
  actions: { flexDirection: "row", gap: 8 },
  acceptBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: hexToRgba(Colors.green, 0.15),
    alignItems: "center",
  },
  acceptText: { color: Colors.green, fontSize: 13, fontWeight: "700" },
  rejectBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: hexToRgba(Colors.red, 0.15),
    alignItems: "center",
  },
  rejectText: { color: Colors.red, fontSize: 13, fontWeight: "700" },
});
