import { StyleSheet } from 'react-native'
import { Colors } from '../../../constants/colors'
import { rgbaFromHex } from '../stake/stakeStyles'

export const gameScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  sectionLabel: {
    marginTop: 12,
    marginBottom: 8,
    marginHorizontal: 16,
    color: Colors.textMuted,
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    fontWeight: '700',
  },
  grid: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  tileCol: { width: '48.5%' },
  tile: {
    position: 'relative',
    width: '100%',
    minHeight: 90,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    backgroundColor: Colors.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tileSelected: { borderColor: Colors.accent, backgroundColor: rgbaFromHex(Colors.accent, 0.2) },
  recentDot: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.accentLight,
  },
  tileEmoji: { fontSize: 32 },
  tileLabel: { marginTop: 8, color: Colors.text, fontSize: 13, fontWeight: '700' },
  tileLabelSelected: { color: Colors.accentLight },
  customWrap: { marginHorizontal: 16, marginTop: 10 },
  customInputWrap: { marginTop: 10 },
  customInput: {
    backgroundColor: Colors.cardAlt,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    color: Colors.text,
    fontSize: 15,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    backgroundColor: Colors.background,
  },
  footerFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: -16,
    height: 16,
    backgroundColor: rgbaFromHex(Colors.background, 0.6),
  },
  nextButton: {
    height: 52,
    borderRadius: 14,
    backgroundColor: Colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  nextButtonDisabled: { backgroundColor: Colors.cardAlt },
  nextMainText: { color: Colors.white, fontSize: 16, fontWeight: '700' },
  nextMainTextDisabled: { color: Colors.textMuted },
  nextSubText: { color: rgbaFromHex(Colors.text, 0.6), fontSize: 12 },
})
