import { StyleSheet } from "react-native";
import { Colors } from "../constants/colors";
import { hexToRgba } from "../utils/colors";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
  header: {
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.cardAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  iconTxt: { color: Colors.text, fontWeight: "700" },
  title: { color: Colors.text, fontWeight: "700", fontSize: 17 },
  statusRow: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 4,
    flexDirection: "row",
    alignItems: "center",
  },
  badge: {
    borderWidth: 1,
    borderRadius: 20,
    paddingVertical: 4,
    paddingHorizontal: 12,
  },
  badgeText: { fontSize: 12, fontWeight: "700" },
  card: {
    marginHorizontal: 16,
    backgroundColor: Colors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    padding: 16,
  },
  vsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  bodyText: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: "600",
    marginTop: 8,
  },
  muted: { color: Colors.textMuted, fontSize: 13 },
  infoRow: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.borderSoft,
    flexDirection: "row",
  },
  sectionLabel: {
    marginLeft: 16,
    marginTop: 16,
    marginBottom: 12,
    color: Colors.textMuted,
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  scoreRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  scoreBox: {
    width: 112,
    height: 84,
    borderRadius: 12,
    backgroundColor: Colors.cardAlt,
    borderWidth: 1,
    borderColor: Colors.cardAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  scoreWinner: {
    borderColor: Colors.green,
    backgroundColor: hexToRgba(Colors.green, 0.12),
  },
  scoreNick: { color: Colors.textMuted, fontSize: 12, marginBottom: 6 },
  scoreValue: { color: Colors.text, fontSize: 32, fontWeight: "700" },
  scoreColon: {
    marginHorizontal: 12,
    color: Colors.textMuted,
    fontSize: 28,
    fontWeight: "700",
  },
  settlementRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  chatRow: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 16,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  input: {
    flex: 1,
    backgroundColor: Colors.cardAlt,
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 14,
    color: Colors.text,
  },
  sendBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
});
