import type { GameTemplate } from './types'

export const SPORT_GAME_TEMPLATES: GameTemplate[] = [
  {
    id: 'pilkarzyki',
    name: 'Piłkarzyki',
    emoji: '⚽',
    category: 'sport',
    resultType: 'score',
    defaultFormat: 'single',
    availableFormats: ['single', 'best_of', 'per_match', 'round_robin', 'elimination', 'session'],
    scoringLabel: 'Bramki',
    winCondition: 'higher_score',
    supportsTeams: true,
    supportsRematch: false,
  },
  {
    id: 'ping_pong',
    name: 'Ping pong',
    emoji: '🏓',
    category: 'sport',
    resultType: 'score',
    defaultFormat: 'single',
    availableFormats: ['single', 'best_of', 'per_match', 'round_robin', 'elimination', 'session'],
    scoringLabel: 'Punkty',
    winCondition: 'higher_score',
    supportsTeams: false,
    supportsRematch: false,
  },
  {
    id: 'dart',
    name: 'Dart',
    emoji: '🎯',
    category: 'sport',
    resultType: 'legs',
    defaultFormat: 'best_of',
    defaultBestOf: 3,
    availableFormats: ['single', 'best_of', 'per_match', 'elimination', 'session'],
    scoringLabel: 'Legi',
    winCondition: 'most_legs',
    supportsTeams: false,
    supportsRematch: false,
  },
  {
    id: 'koszykowka',
    name: 'Koszykówka 1v1',
    emoji: '🏀',
    category: 'sport',
    resultType: 'score',
    defaultFormat: 'single',
    availableFormats: ['single', 'best_of', 'per_match', 'session'],
    scoringLabel: 'Punkty',
    winCondition: 'higher_score',
    supportsTeams: false,
    supportsRematch: false,
  },
  {
    id: 'tenis',
    name: 'Tenis',
    emoji: '🎾',
    category: 'sport',
    resultType: 'sets',
    defaultFormat: 'best_of',
    defaultBestOf: 3,
    availableFormats: ['single', 'best_of', 'session'],
    scoringLabel: 'Sety',
    winCondition: 'most_sets',
    supportsTeams: false,
    supportsRematch: false,
  },
  {
    id: 'badminton',
    name: 'Badminton',
    emoji: '🏸',
    category: 'sport',
    resultType: 'score',
    defaultFormat: 'single',
    availableFormats: ['single', 'best_of', 'session'],
    scoringLabel: 'Punkty',
    winCondition: 'higher_score',
    supportsTeams: false,
    supportsRematch: false,
  },
  {
    id: 'bilard',
    name: 'Bilard',
    emoji: '🎱',
    category: 'sport',
    resultType: 'winner_only',
    defaultFormat: 'single',
    availableFormats: ['single', 'best_of', 'per_match', 'round_robin', 'elimination', 'session'],
    scoringLabel: null,
    winCondition: 'winner_only',
    supportsTeams: false,
    supportsRematch: false,
  },
  {
    id: 'bowling',
    name: 'Bowling',
    emoji: '🎳',
    category: 'sport',
    resultType: 'score',
    defaultFormat: 'single',
    availableFormats: ['single', 'round_robin', 'elimination', 'session'],
    scoringLabel: 'Punkty',
    winCondition: 'higher_score',
    supportsTeams: false,
    supportsRematch: false,
  },
]
