import type { GameTemplate } from './types'

export const BOARD_GAME_TEMPLATES: GameTemplate[] = [
  {
    id: 'szachy',
    name: 'Szachy',
    emoji: '♟️',
    category: 'planszowe',
    resultType: 'winner_only',
    defaultFormat: 'single',
    availableFormats: ['single', 'best_of', 'session'],
    scoringLabel: null,
    winCondition: 'winner_only',
    supportsTeams: false,
    supportsRematch: true,
  },
  {
    id: 'poker',
    name: 'Poker',
    emoji: '🃏',
    category: 'planszowe',
    resultType: 'chips',
    defaultFormat: 'single',
    availableFormats: ['single', 'session'],
    scoringLabel: null,
    winCondition: 'chip_count',
    supportsTeams: false,
    supportsRematch: false,
    pokerModes: ['winner_takes_all', 'chip_count'],
    supportsRebuy: true,
    defaultStack: 3000,
    defaultRebuyStack: 1500,
  },
  {
    id: 'uno',
    name: 'UNO',
    emoji: '🃏',
    category: 'planszowe',
    resultType: 'winner_only',
    defaultFormat: 'single',
    availableFormats: ['single', 'session'],
    scoringLabel: null,
    winCondition: 'winner_only',
    supportsTeams: false,
    supportsRematch: false,
  },
]
