import type { GameTemplate } from './types'

export const VIDEO_GAME_TEMPLATES: GameTemplate[] = [
  {
    id: 'clash_royale',
    name: 'Clash Royale',
    emoji: '🏰',
    category: 'video',
    resultType: 'score',
    defaultFormat: 'per_match',
    availableFormats: ['single', 'best_of', 'per_match', 'round_robin', 'elimination', 'session'],
    scoringLabel: 'Korony',
    winCondition: 'higher_score',
    supportsTeams: false,
    supportsRematch: false,
  },
  {
    id: 'fifa',
    name: 'FIFA / EA FC',
    emoji: '⚽🎮',
    category: 'video',
    resultType: 'score',
    defaultFormat: 'single',
    availableFormats: ['single', 'best_of', 'per_match', 'round_robin', 'elimination', 'session'],
    scoringLabel: 'Bramki',
    winCondition: 'higher_score',
    supportsTeams: false,
    supportsRematch: true,
  },
  {
    id: 'bijatyki',
    name: 'Bijatyki (Tekken/SF)',
    emoji: '🥊',
    category: 'video',
    resultType: 'winner_only',
    defaultFormat: 'best_of',
    defaultBestOf: 3,
    availableFormats: ['single', 'best_of', 'elimination', 'session'],
    scoringLabel: null,
    winCondition: 'winner_only',
    supportsTeams: false,
    supportsRematch: false,
  },
  {
    id: 'rocket_league',
    name: 'Rocket League',
    emoji: '🚗',
    category: 'video',
    resultType: 'score',
    defaultFormat: 'single',
    availableFormats: ['single', 'best_of', 'round_robin', 'elimination', 'session'],
    scoringLabel: 'Bramki',
    winCondition: 'higher_score',
    supportsTeams: true,
    supportsRematch: false,
  },
  {
    id: 'nba2k',
    name: 'NBA 2K',
    emoji: '🏀🎮',
    category: 'video',
    resultType: 'score',
    defaultFormat: 'single',
    availableFormats: ['single', 'best_of', 'round_robin', 'elimination', 'session'],
    scoringLabel: 'Punkty',
    winCondition: 'higher_score',
    supportsTeams: false,
    supportsRematch: false,
  },
]
