name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npx --no-install tsc --noEmit
      - run: npm run lint
      - run: npm test -- --ci --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: npm run check:knip
        continue-on-error: true
      - run: npx --no-install expo-doctor@1.20.2
        continue-on-error: true
      - run: npm audit --audit-level=high
        continue-on-error: true
      - name: Danger
        if: github.event_name == 'pull_request'
        run: npx --no-install danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
