import { StyleSheet } from 'react-native'
import { Colors } from '../../constants/colors'

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#0f1117' },
  centered: { flex: 1, backgroundColor: '#0f1117', justifyContent: 'center', alignItems: 'center' },
  errorText: { color: 'rgba(232,230,224,0.5)', fontSize: 15 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 56, paddingBottom: 12 },
  backBtn: { width: 80 },
  backText: { fontSize: 14, color: '#7F77DD' },
  headerTitle: { fontSize: 16, fontWeight: '600', color: '#e8e6e0' },
  scroll: { flex: 1 },
  scrollContent: { padding: 20, paddingBottom: 40 },
  gameCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#181c24', borderRadius: 16, borderWidth: 0.5, borderColor: '#1e2330', padding: 18, marginBottom: 24, gap: 14 },
  gameEmoji: { fontSize: 36 },
  gameInfo: { flex: 1 },
  gameName: { fontSize: 18, fontWeight: '700', color: '#e8e6e0', marginBottom: 4 },
  gameFormat: { fontSize: 13, color: 'rgba(232,230,224,0.5)' },
  statusBadge: { borderRadius: 20, paddingHorizontal: 12, paddingVertical: 5 },
  statusText: { fontSize: 12, fontWeight: '700' },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 13, fontWeight: '600', color: 'rgba(232,230,224,0.5)', textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 12 },
  participantCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#181c24', borderRadius: 14, borderWidth: 0.5, borderColor: '#1e2330', padding: 14, marginBottom: 8 },
  participantLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  avatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#1e2330', justifyContent: 'center', alignItems: 'center' },
  avatarMe: { backgroundColor: '#534AB730' },
  avatarText: { fontSize: 16, fontWeight: '700', color: '#7F77DD' },
  nickRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 3 },
  participantNick: { fontSize: 14, fontWeight: '600', color: '#e8e6e0' },
  youBadge: { backgroundColor: '#1e2330', borderRadius: 20, paddingHorizontal: 7, paddingVertical: 2 },
  youText: { fontSize: 10, color: 'rgba(232,230,224,0.4)' },
  participantRole: { fontSize: 12, color: 'rgba(232,230,224,0.4)' },
  participantRight: { alignItems: 'flex-end', gap: 3 },
  participantStake: { fontSize: 15, fontWeight: '700', color: '#e8e6e0' },
  participantOdds: { fontSize: 12, color: 'rgba(232,230,224,0.4)' },
  scoreRow: { marginBottom: 16 },
  scoreInput: { backgroundColor: '#181c24', borderWidth: 0.5, borderColor: '#1e2330', borderRadius: 12, padding: 14, fontSize: 24, color: '#e8e6e0', textAlign: 'center', letterSpacing: 2 },
  resolveHint: { fontSize: 13, color: 'rgba(232,230,224,0.5)', marginBottom: 10 },
  resolveButtons: { gap: 10 },
  resolveBtn: { backgroundColor: '#181c24', borderWidth: 0.5, borderColor: '#1e2330', borderRadius: 12, padding: 16, alignItems: 'center' },
  resolveBtnPrimary: { backgroundColor: '#1D9E75', borderColor: '#1D9E75' },
  resolveBtnHighlight: { borderColor: '#7F77DD' },
  resolveBtnSelected: { backgroundColor: '#534AB730', borderColor: '#534AB7' },
  disputeBtn: { backgroundColor: '#E24B4A', borderColor: '#E24B4A' },
  resolveBtnText: { fontSize: 15, fontWeight: '600', color: '#e8e6e0' },
  enterResultBtn: { backgroundColor: '#534AB7', borderRadius: 12, padding: 16, alignItems: 'center' },
  enterResultBtnText: { fontSize: 16, fontWeight: '700', color: '#fff' },
  waitingOrganizerCard: { backgroundColor: '#181c24', borderRadius: 12, borderWidth: 0.5, borderColor: '#1e2330', padding: 16 },
  waitingOrganizerText: { fontSize: 14, color: 'rgba(232,230,224,0.65)', lineHeight: 20 },
  waitingOrganizerName: { color: '#e8e6e0', fontWeight: '700' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)', justifyContent: 'center', padding: 24 },
  modalCard: { backgroundColor: '#181c24', borderRadius: 16, borderWidth: 0.5, borderColor: '#1e2330', padding: 20 },
  modalTitle: { fontSize: 18, fontWeight: '700', color: '#e8e6e0', marginBottom: 16 },
  modalScoreInput: { backgroundColor: '#0f1117', borderWidth: 0.5, borderColor: '#1e2330', borderRadius: 12, padding: 14, fontSize: 22, color: '#e8e6e0', textAlign: 'center', letterSpacing: 2, marginBottom: 16 },
  modalActions: { flexDirection: 'row', gap: 12, marginTop: 20 },
  modalCancelBtn: { flex: 1, backgroundColor: '#1e2330', borderRadius: 12, padding: 14, alignItems: 'center' },
  modalCancelText: { fontSize: 15, fontWeight: '600', color: 'rgba(232,230,224,0.7)' },
  modalSubmitBtn: { flex: 1, backgroundColor: '#1D9E75', borderRadius: 12, padding: 14, alignItems: 'center' },
  modalSubmitDisabled: { opacity: 0.6 },
  modalSubmitText: { fontSize: 15, fontWeight: '700', color: '#fff' },
  pendingResultCard: { backgroundColor: '#181c24', borderRadius: 12, borderWidth: 0.5, borderColor: '#1e2330', padding: 14, gap: 6, marginBottom: 10 },
  pendingResultText: { fontSize: 14, color: 'rgba(232,230,224,0.6)' },
  pendingResultValue: { color: '#e8e6e0', fontWeight: '700' },
  waitingText: { fontSize: 13, color: 'rgba(232,230,224,0.5)' },
  settlementCard: { backgroundColor: '#181c24', borderRadius: 14, borderWidth: 0.5, borderColor: '#1e2330', padding: 16, marginBottom: 10, gap: 12 },
  settlementPaid: { opacity: 0.5 },
  settlementLine: { fontSize: 15, lineHeight: 22, color: '#e8e6e0' },
  settlementName: { color: '#e8e6e0', fontWeight: '600' },
  settlementOwes: { color: 'rgba(232,230,224,0.55)', fontWeight: '400' },
  settlementAmountInLine: { fontSize: 15, fontWeight: '700', color: '#E24B4A' },
  paidBadge: { alignSelf: 'flex-start' },
  paidText: { fontSize: 13, color: '#1D9E75', fontWeight: '600' },
  settlementActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  payBtn: { flex: 1, minWidth: 120, backgroundColor: '#534AB7', borderRadius: 10, padding: 12, alignItems: 'center' },
  payBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  remindBtn: {
    flex: 1,
    minWidth: 120,
    backgroundColor: '#EF9F2718',
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: '#EF9F27',
  },
  remindBtnText: { color: '#EF9F27', fontSize: 14, fontWeight: '600' },
  emptyCard: { backgroundColor: '#181c24', borderRadius: 14, borderWidth: 0.5, borderColor: '#1e2330', padding: 24, alignItems: 'center' },
  emptyText: { fontSize: 14, color: 'rgba(232,230,224,0.4)' },
  matchRow: {
    backgroundColor: Colors.card,
    borderRadius: 12,
    borderWidth: 0.5,
    borderColor: Colors.border,
    padding: 14,
    marginBottom: 8,
  },
  matchRowText: { fontSize: 14, color: Colors.text, lineHeight: 20 },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.card,
    borderRadius: 12,
    borderWidth: 0.5,
    borderColor: Colors.border,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  balanceNick: { fontSize: 14, fontWeight: '600', color: Colors.text },
  balanceAmount: { fontSize: 15, fontWeight: '700' },
  endSessionBtn: {
    marginTop: 10,
    backgroundColor: Colors.cardAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.amber,
    padding: 16,
    alignItems: 'center',
  },
  endSessionBtnText: { fontSize: 15, fontWeight: '700', color: Colors.amber },
})
